### PR TITLE
Pull Request #1

### PR DESCRIPTION
**Pull request by Jesus0204**
Prueba de Pull Request

### CODE REVIEW

**Comment by DiegoGarciaPadilla** [comment]
No apruebo 🙅‍♂️

**Review by Dieg0Lir4 — CHANGES_REQUESTED** [review]
'REQUEST_CHANGES' performed by Xcode.

**Comment by Dieg0Lir4** [comment]
yo si apruebo

**Review by Dieg0Lir4 — CHANGES_REQUESTED** [review]
'REQUEST_CHANGES' performed by Xcode.

**Review by MariaJoseGaytan — APPROVED** [review]
'APPROVE' performed by Xcode.

**Review by Dieg0Lir4 — APPROVED** [review]
'APPROVE' performed by Xcode.

**Review by DiegoGarciaPadilla — CHANGES_REQUESTED** [review]
no sigue el estandar

**Review by Dieg0Lir4 — CHANGES_REQUESTED** [review]
'REQUEST_CHANGES' performed by Xcode.

**Comment by Dieg0Lir4** [comment]
Tienes razon, no sigue el estandar

**Comment by DiegoGarciaPadilla** [comment]
¿Ya pasaste el SwiftLint?

**Pull request merged**
