### PR TITLE
No saques la bici

### PR DESCRIPTION
**Pull request by Dieg0Lir4**
Porfa aprueben, es que necesito 3 historias de usuario

### CODE REVIEW

**Review by DiegoGarciaPadilla — CHANGES_REQUESTED** [review]
No sigue el estandar

**Review by Jesus0204 — CHANGES_REQUESTED** [review]
'REQUEST_CHANGES' performed by Xcode.

**Review by MariaJoseGaytan — APPROVED** [review]
'APPROVE' performed by Xcode.

**Review by MariaJoseGaytan — CHANGES_REQUESTED** [review]
'REQUEST_CHANGES' performed by Xcode.

**Review by MariaJoseGaytan — DISMISSED** [review]
'APPROVE' performed by Xcode.

**Review by Jesus0204 — DISMISSED** [review]
'APPROVE' performed by Xcode.

**Comment by Dieg0Lir4** [comment]
sabes que, al fin y al cabo ni queria

**Review by DiegoGarciaPadilla — DISMISSED** [review]
Te lo apruebo por lastima

**Review by DiegoGarciaPadilla — APPROVED** [review]
por lastima

**Pull request merged**
